### ISSUE TITLE
我在pnpm run db:init初始化时报错，不知道哪里有问题

### ISSUE THREAD

**Issue by kaikee-Snow** [AprilNEA/ChatGPT-Admin-Web#181]
PrismaClientKnownRequestError: 
Invalid `prisma.model.createMany()` invocation in
/root/kaikee/chatgpt-admin/ChatGPT-Admin-Web/prisma/seed.ts:6:37

  3 const prisma = new PrismaClient();
  4 
  5 async function main() {
→ 6   const models = await prisma.model.createMany(
Unique constraint failed on the fields: (`id`)
    at ni.handleRequestError (/root/kaikee/chatgpt-admin/ChatGPT-Admin-Web/prisma/client/runtime/library.js:124:6817)
    at ni.handleAndLogRequestError (/root/kaikee/chatgpt-admin/ChatGPT-Admin-Web/prisma/client/runtime/library.js:124:6206)
    at ni.request (/root/kaikee/chatgpt-admin/ChatGPT-Admin-Web/prisma/client/runtime/library.js:124:5926)
    at async l (/root/kaikee/chatgpt-admin/ChatGPT-Admin-Web/prisma/client/runtime/library.js:129:10023)
    at async main (/root/kaikee/chatgpt-admin/ChatGPT-Admin-Web/prisma/seed.ts:6:18) {
  code: 'P2002',
  clientVersion: '5.6.0',
  meta: { target: [ 'id' ] }
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed.ts
 ELIFECYCLE  Command failed with exit code 1.

**Comment by AprilNEA** [comment]
请确保数据库未经过初始化并检查是否为最新版。
