### ISSUE TITLE
大佬们，UpstashError这该怎么解决？

### ISSUE THREAD

**Issue by chenzhongd** [AprilNEA/ChatGPT-Admin-Web#41]
[SERVER ERROR] UpstashError: Unauthorized
    at HttpClient.request (/var/task/apps/chat/.next/server/chunks/371.js:11258:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async JsonGetCommand.exec (/var/task/apps/chat/.next/server/chunks/371.js:5965:37)
    at async UserDAL.readJSONProperty (/var/task/apps/chat/.next/server/chunks/38.js:82:17)
    at async UserLogic.login (/var/task/apps/chat/.next/server/chunks/38.js:1133:30)
    at async POST (/var/task/apps/chat/.next/server/app/api/user/login/route.js:177:14)
    at async /var/task/apps/chat/.next/server/chunks/150.js:3458:33

按照说明文档配置好了Upstash的url和token

**Comment by AprilNEA** [comment]
填写的是 Token 不是 Password
